name: Atualizar dados FIIs

on:
  schedule:
    - cron: '0 3 * * *'    # Executa todos os dias às 03:00 UTC (00:00 Brasil)
  workflow_dispatch:        # Permite executar manualmente também

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script principal com pasta padrão
      run: |
        python app.py output/dados_projeto

    - name: Versionar e subir dados atualizados
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add output/*.csv
        git commit -m '📊 Atualização automática dos dados [GitHub Actions]'
        git push
